# @TODO: Prefer Json - Gatsby depends on this unfortunately.
siteTitle="Mohamed H. Mohamed"
siteUrl="http://mohamedtwice.com"
description="Mohamed H. Mohamed is a full-stack developer working with individuals, nonprofits and small businesses across the world."
